events {}

http {
    upstream predictive_maintenance_api {
        server stable:8000 weight=9;
        server canary:8000 weight=1;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://predictive_maintenance_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
